name: "Merge branch rules"
on:
  pull_request:
    branches:
      - production
      - staging
      - "release/*"
    types:
      - closed
jobs:
  standard-version:
    if: github.event.pull_request.merged == true
    uses: bilwifi/gh-action-test/.github/workflows/generic-standard-version-branch-rules.yml@main
    with: 
      main: "production"
      isPackage: false
      isAppExpo: true
    secrets: inherit
  build-app:
    needs: standard-version
    if: github.event.pull_request.merged == true
    uses: bilwifi/gh-action-test/.github/workflows/generic-react-build.yml@main
    with: 
      branch: ${{ github.event.pull_request.base.ref }}
    secrets: inherit
 
