name: "Merge branch rules"
on:
  pull_request:
    branches:
      - production
      - staging
      - "release/*"
    types:
      - closed
jobs:
  merged-branch-rules:
    uses: napp-inc/gh-actions/.github/workflows/generic-merge-branch-rules.yml@main
    with: 
      isAppReact: true
      main: "production"
    secrets: inherit
